### ISSUE TITLE
Error: sending on closed connection

### ISSUE THREAD

**Issue by thomasyeung687** [nbd-wtf/nostr-tools#370] opened 2024-02-20 02:34 UTC
For some reason after a certain amount of time nostr-tools returns an error:
Error: sending on closed connection

I am leaving the connections open in order to fetch chats in real time. Is this not the way nostr-tools is intended to be used?

Thanks for your time btw and this package is great!

**Comment by fiatjaf** [comment] 2024-02-20 03:05
Yes, it is definitely intended for connections to be left open.

But maybe some connection is going down for some reason (on the relay side probably) and we're not handling that very well.

**Comment by thomasyeung687** [comment] 2024-02-20 03:46
Is there a way I can wrap it in a try catch to catch this error? I have try catches around the areas where I am subscribing to the relays but its not catching it for some reason

**Comment by thomasyeung687** [comment] 2024-02-20 03:46
Or perhaps this might need to be a bug ticket or a feature ticket added to the backlog?

**Comment by j3ko** [comment] 2024-03-16 00:06
For me, it occurs when the subscription is closed at this line:

https://github.com/nbd-wtf/nostr-tools/blob/71456feb20fb69cea80fb2fdda6e09816809a7d1/abstract-relay.ts#L344

**Comment by j3ko** [comment] 2024-03-16 12:18
I took a second look at this since it's become a bit of a blocker for me.

A minimal fix is in the PR #387. The problem is that `connectionPromise` is unset before `closeAllSubscriptions`, which sometimes needs `connectionPromise`.

A bigger concern is if there are other exceptions in the async `onclose`, `onerror`, `onopen` callbacks, they are unhandled and will crash the running application. I think a way to fix this is to use try/catch in each function and call reject where there is an error, so the application can handle the errors gracefully.

**Closed** 2024-03-16 16:29 UTC
